-- Supabase Vector Store schema for RaizitoBot RAG.
-- Run this in Supabase SQL Editor before setting RAG_VECTOR_BACKEND=supabase.
-- The bot writes through SUPABASE_SERVICE_ROLE_KEY on the server.

create extension if not exists vector with schema extensions;

create table if not exists public.knowledge_items (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    source_type text not null,
    source_id text not null,
    title text not null,
    content text not null,
    embedding vector(256) not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (user_id, source_type, source_id)
);

alter table public.knowledge_items enable row level security;

create index if not exists idx_knowledge_items_user_source
on public.knowledge_items (user_id, source_type);

create index if not exists idx_knowledge_items_embedding
on public.knowledge_items
using ivfflat (embedding vector_cosine_ops)
with (lists = 100);

create or replace function public.match_knowledge_items(
    query_embedding vector(256),
    target_user_id bigint,
    match_count integer default 5,
    match_threshold double precision default 0.05,
    filter_source_type text default null
)
returns table (
    id bigint,
    user_id bigint,
    source_type text,
    source_id text,
    title text,
    content text,
    metadata jsonb,
    similarity double precision
)
language plpgsql
stable
as $$
begin
    return query
    select
        ki.id,
        ki.user_id,
        ki.source_type,
        ki.source_id,
        ki.title,
        ki.content,
        ki.metadata,
        1 - (ki.embedding <=> query_embedding) as similarity
    from public.knowledge_items as ki
    where ki.user_id in (0, target_user_id)
      and (filter_source_type is null or ki.source_type = filter_source_type)
      and (1 - (ki.embedding <=> query_embedding)) >= match_threshold
    order by ki.embedding <=> query_embedding
    limit match_count;
end;
$$;
